# Generated by Django 4.2.15 on 2024-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ordering_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('executioner', models.CharField(max_length=20)),
                ('direct', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField()),
            ],
        ),
    ]
