# Generated by Django 4.2.15 on 2024-08-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderingtask',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
