# Generated by Django 4.2.15 on 2024-08-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderingtask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='orderingtask',
            name='description',
            field=models.TextField(),
        ),
    ]
