# Generated by Django 4.2.15 on 2024-09-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_alter_orderingtask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderingtask',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
