# Generated by Django 4.2.15 on 2024-09-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderingtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderingtask',
            name='status',
        ),
    ]
