# Generated by Django 4.2.15 on 2024-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_orderingtask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('executioner', models.CharField(max_length=20)),
                ('direct', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('startTime', models.DateTimeField(auto_now=True)),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='orderingtask',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
