# Generated by Django 4.2.15 on 2024-09-19 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_task_orderingtask_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordering',
        ),
        migrations.DeleteModel(
            name='OrderingTask',
        ),
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
